apiVersion: v2
name: routemap-operator
description: >-
  A Kubernetes operator that builds a live route map of your cluster's HTTP
  endpoints
type: application
version: 0.1.1
appVersion: 0.1.1
keywords:
  - kubernetes
  - operator
  - routing
  - ingress
  - gateway-api
home: https://github.com/dmakeienko/routemap-operator
sources:
  - https://github.com/dmakeienko/routemap-operator
maintainers:
  - name: dmakeienko
