apiVersion: routemaps.github.com/v1alpha1
kind: Routemap
metadata:
  name: routemap-sample
  namespace: default
  labels:
    app.kubernetes.io/name: routemap-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  displayName: "Sample Route Map"
  namespaces:
    watchAll: true
  sources:
    - Ingress
    - HTTPRoute
  healthCheck:
    enabled: true
    annotationKey: routemap.github.com/healthcheck
    interval: 30s
    timeout: 5s
    expectedStatus: 200
